"""
Flask web interface for the Polymarket Whale Bot.

Run with:
    python web_app.py

Then open http://localhost:5000 in your browser.
"""
from __future__ import annotations

import os
from pathlib import Path

from flask import Flask, jsonify, redirect, render_template, request, url_for

import state

app = Flask(__name__)
app.secret_key = os.urandom(24)

ENV_FILE = Path(__file__).parent / ".env"


# ── Helpers ───────────────────────────────────────────────────────────────────

def _env_vals() -> dict:
    """Read current .env values for prefilling the setup form."""
    vals: dict = {
        "api_id": "", "api_hash": "", "phone": "",
        "private_key": "",
        "max_trade": "20", "min_whale": "5000", "scale": "0.001",
        "dry_run": "true",
    }
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            k, _, v = line.partition("=")
            mapping = {
                "TELEGRAM_API_ID": "api_id",
                "TELEGRAM_API_HASH": "api_hash",
                "TELEGRAM_PHONE": "phone",
                "POLYGON_PRIVATE_KEY": "private_key",
                "MAX_TRADE_SIZE_USDC": "max_trade",
                "MIN_WHALE_SIZE_USDC": "min_whale",
                "COPY_SCALE_FACTOR": "scale",
                "DRY_RUN": "dry_run",
            }
            if k in mapping:
                vals[mapping[k]] = v.strip()
    return vals


def _write_env(data: dict) -> None:
    """Write .env file from form data."""
    dry = "true" if data.get("dry_run") else "false"
    content = f"""# Auto-generated by Whale Bot web interface
TELEGRAM_API_ID={data['api_id']}
TELEGRAM_API_HASH={data['api_hash']}
TELEGRAM_PHONE={data['phone']}
WHALE_BOT_USERNAME=PredictionRadarBot
TELEGRAM_SESSION_NAME=polymarket_watcher

POLYGON_PRIVATE_KEY={data['private_key']}
CLOB_API_URL=https://clob.polymarket.com
GAMMA_API_URL=https://gamma-api.polymarket.com

MAX_TRADE_SIZE_USDC={data.get('max_trade', 20)}
MAX_TRADE_PCT=0.05
MIN_WHALE_SIZE_USDC={data.get('min_whale', 5000)}
COPY_SCALE_FACTOR={data.get('scale', 0.001)}
MIN_PROBABILITY=0.05
MAX_PROBABILITY=0.95
SLIPPAGE_TOLERANCE=0.02
MARKET_COOLDOWN_SECS=300

LOG_LEVEL=INFO
DRY_RUN={dry}
"""
    ENV_FILE.write_text(content)
    # Reload env vars into os.environ immediately
    for line in content.splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            os.environ[k.strip()] = v.strip()


def _cfg_summary() -> dict:
    return {
        "max_trade": os.getenv("MAX_TRADE_SIZE_USDC", "20"),
        "min_whale": os.getenv("MIN_WHALE_SIZE_USDC", "5000"),
        "scale_pct": f"{float(os.getenv('COPY_SCALE_FACTOR', '0.001')) * 100:.2f}",
        "min_prob": int(float(os.getenv("MIN_PROBABILITY", "0.05")) * 100),
        "max_prob": int(float(os.getenv("MAX_PROBABILITY", "0.95")) * 100),
        "cooldown": os.getenv("MARKET_COOLDOWN_SECS", "300"),
    }


def _is_configured() -> bool:
    v = _env_vals()
    return bool(v["api_id"] and v["api_hash"] and v["phone"] and v["private_key"])


# ── Routes ────────────────────────────────────────────────────────────────────

@app.route("/")
def index():
    if not _is_configured():
        return redirect(url_for("setup_get"))
    state.load_trades()
    return render_template(
        "dashboard.html",
        bot_running=state.bot_running,
        logs=state.log_lines[-100:],
        trades=state.trades,
        whale_stats=state.whale_stats,
        dry_run=(os.getenv("DRY_RUN", "true").lower() == "true"),
        cfg=_cfg_summary(),
    )


@app.route("/setup", methods=["GET"])
def setup_get():
    return render_template("setup.html", vals=_env_vals(), error=None)


@app.route("/setup", methods=["POST"])
def setup_post():
    data = request.form.to_dict()
    errors = []
    if not data.get("api_id", "").strip().isdigit():
        errors.append("API ID mora biti broj.")
    if len(data.get("api_hash", "")) < 20:
        errors.append("API Hash izgleda prekratak.")
    if not data.get("phone", "").startswith("+"):
        errors.append("Broj telefona mora poceti s '+' (npr. +38160...).")
    if len(data.get("private_key", "")) < 60:
        errors.append("Private key izgleda nekompletan.")

    if errors:
        return render_template("setup.html", vals=data, error=" | ".join(errors))

    _write_env(data)
    state.add_log("INFO", "Podesavanja sacuvana.")
    return redirect(url_for("index"))


# ── API endpoints (called by dashboard JS) ────────────────────────────────────

@app.route("/api/logs")
def api_logs():
    return jsonify({
        "logs": state.log_lines[-100:],
        "running": state.bot_running,
    })


@app.route("/api/stats")
def api_stats():
    live = sum(1 for t in state.trades if not t.get("dry_run"))
    spent = sum(t.get("size_usdc", 0) for t in state.trades)
    return jsonify({
        "total": len(state.trades),
        "spent": spent,
        "live": live,
        "whales": len(state.whale_stats),
        "running": state.bot_running,
    })


@app.route("/api/bot/start", methods=["POST"])
def api_start():
    if state.bot_running:
        return jsonify({"ok": False, "msg": "already running"})
    if not _is_configured():
        return jsonify({"ok": False, "msg": "not configured"})
    try:
        from bot_runner import runner
        runner.start()
        return jsonify({"ok": True})
    except Exception as exc:
        state.add_log("ERROR", f"Start failed: {exc}")
        return jsonify({"ok": False, "msg": str(exc)})


@app.route("/health")
def health():
    """Simple health-check endpoint for uptime monitors / Docker HEALTHCHECK."""
    live = sum(1 for t in state.trades if not t.get("dry_run"))
    return jsonify({
        "status": "ok",
        "bot_running": state.bot_running,
        "trades_total": len(state.trades),
        "trades_live": live,
        "configured": _is_configured(),
    }), 200


@app.route("/api/bot/stop", methods=["POST"])
def api_stop():
    if not state.bot_running:
        return jsonify({"ok": False, "msg": "not running"})
    try:
        from bot_runner import runner
        runner.stop()
        return jsonify({"ok": True})
    except Exception as exc:
        return jsonify({"ok": False, "msg": str(exc)})


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    state.load_trades()
    print("\n🐋  Polymarket Whale Bot")
    print("   Otvori http://localhost:5000 u browseru\n")
    app.run(host="0.0.0.0", port=5000, debug=False)
